agent {
    data_dir = "/opt/spire/data"
    log_level = "DEBUG"
    server_address = "spire-server"
    server_port = "8081"
    socket_path = "/tmp/spire-agent/public/api.sock"
    trust_domain = "blog.local"
    insecure_bootstrap = true
    join_token = "3754bd6b-67ce-41d4-be94-ffddd67fe2d4"
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }
    KeyManager "disk" {
        plugin_data {
            directory = "/opt/spire/data"
        }
    }
    WorkloadAttestor "docker" {
        plugin_data {
        }
    }
}